### ISSUE TITLE
Bug in scan module

### ISSUE THREAD

**Issue by kirillwow** [alphasoc/flightsim#14]
For sure you mistyped with a counter in [scan.go](https://github.com/alphasoc/flightsim/blob/master/simulator/scan.go#L67)
There should be 'j' instead of 'i'

This bug cause flightsim to connect to the same port 10 times in a row
![image](https://user-images.githubusercontent.com/36988916/60819783-df090a00-a1a8-11e9-8941-bd0667cb2c0a.png)

**Comment by tg** [comment]
Good spot, thanks for reporting. Will push a new release this week with a fix.
