### ISSUE TITLE
Direct traffic to specific interface

### ISSUE THREAD

**Issue by jlawre23** [alphasoc/flightsim#4]
Is there a way I can direct the traffic to a specific interface like you can with tcpreplay?  I want to send the traffic to an interface I have a sensor attached directly to in order to sniff the traffic.

**Comment by chrisforce1** [comment]
Indeed. Just use `--interface` with the `run` command, as shown below.

```
$ ./flightsim run --help
Run all simulators (default) or a particular test

Usage:
  flightsim run [c2-dns|dga|scan|tunnel] [flags]

Flags:
      --fast               run simulator fast without sleep intervals
  -h, --help               help for run
  -i, --interface string   network interface to use
```

**Comment by jlawre23** [comment]
Sorry for wasting your time.  I completely overlooked that option when looking for it. :|

**Comment by chrisforce1** [comment]
All good!
