### ISSUE TITLE
New module: telegram-bot

### ISSUE THREAD

**Issue by chrisforce1** [alphasoc/flightsim#61]
We should connect to `api.telegram.org` and synthesize API bot traffic, i.e.

https://gbhackers.com/telerat-malware-abused-telegram-bot-api/

![image](https://user-images.githubusercontent.com/4320651/219104644-b07f82f7-ab99-4e64-9514-e2d4b62f262f.png)

**Comment by tg** [comment]
Released in v2.4.0
