### ISSUE TITLE
Make "go install @latest" install v2, not v1

### ISSUE THREAD

**Issue by tg** [alphasoc/flightsim#68]
The readme says flightsim can be installed using the following command:
```
go install github.com/alphasoc/flightsim@latest
```
However, it installs the latest v1 version (v1.1.1), not v2.

**Comment by chrisforce1** [comment]
@tg @ioj please let's fix this?

**Comment by BSidesLuanda** [comment]
Hello,

I run the installation command, but it seems to not installing, because: flightsim: command not found

Env: Kali Linux ARM64

**Comment by chrisforce1** [comment]
> Hello,
> 
> I run the installation command, but it seems to not installing, because: flightsim: command not found
> 
> Env: Kali Linux ARM64

@BSidesLuanda how about if you run it using `./flightsim` instead?

**Comment by BSidesLuanda** [comment]
When I run the install command, here the output that I get.

└─$ go install github.com/alphasoc/flightsim@latest
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/spf13/cobra
go: finding module for package github.com/fatih/color
go: found github.com/fatih/color in github.com/fatih/color v1.16.0
go: found github.com/spf13/cobra in github.com/spf13/cobra v1.8.0
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1

And I don't find the flightsim file to run as you suggested.

**Comment by tg** [comment]
This should be fixed now. Please use the following command (note `v2` at the end):

```
go install github.com/alphasoc/flightsim/v2@latest
```

If the problem persist, try:

```
go clean -cache
```

Closing for now. Feel free to re-open if needed.

**Comment by ioj** [comment]
@BSidesLuanda `go install` places executables in the directory named by the `GOBIN` environment variable, which defaults to `$GOPATH/bin` or `$HOME/go/bin` if the `GOPATH` environment variable is not set.

Please make sure that that directory is in your `PATH`.
