### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by c0d3xpl0it** [alphasoc/flightsim#8]
Whenever we use any module for eg. c2-dns. It generates 10 c2 domains. The no. of domains to be generated should be configurable by using some parameters

Sample Eg:- flightsim run c2-dns **-n 20**

**Comment by krhubert** [comment]
Hi,

Thanks for pointing this out. In version [v1.0.4](https://github.com/alphasoc/flightsim/releases/tag/v1.0.4) there is `-n` parametr.
